version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: node:8
    steps:
      - checkout
      - run:
        name: Install deps
        command: |
          cd archive
          npm install
      - deploy:
          name: Deploy
          command: ./archive/node_modules/.bin/ft-graphics-deploy --assets-prefix=https://ig.ft.com/v2/__assets/
